- name: check value is greater than 100 or not
  hosts: local
  connection: local
  vars: 
    my_number: 75
  tasks:
  - name: print if number greater than 100
    ansible.builtin.debug:
     msg: "given number {{ my_number }} is greater than 100"
    when: my_number > 100

  - name: print if number less than or equal to 100
    ansible.builtin.debug:
      msg: "Given number {{ my_number }} is less than or equal to 100"
    when: my_number <= 100